### ISSUE TITLE
unicode error squashing an image

### ISSUE THREAD

**Issue by bparees** [goldmann/docker-scripts#13]
```
2015-05-12 18:06:00,691 root         INFO     Squashing image 'openshift/perl-516-centos7-candidate'...
2015-05-12 18:06:00,748 root         INFO     Old image has 13 layers
2015-05-12 18:06:00,748 root         INFO     Attempting to squash from layer a0dd78b24d0bb9f011aaf5ab26adc5e07c7d12c2bb796622fd17e46f8632b13b...
2015-05-12 18:06:00,748 root         INFO     Checking if squashing is necessary...
2015-05-12 18:06:00,748 root         INFO     We have 9 layers to squash
2015-05-12 18:06:00,749 root         INFO     Saving image 8fc76b1b4170a0ec291f0f8764d6fda6eec49b35478f668863ffd5929f298b59 to /tmp/tmp-docker-squash-PzH66I/image.tar file...
2015-05-12 18:06:24,545 root         INFO     Image saved!
2015-05-12 18:06:24,547 root         INFO     Unpacking /tmp/tmp-docker-squash-PzH66I/image.tar tar file to /tmp/tmp-docker-squash-PzH66I/old directory
2015-05-12 18:06:27,427 root         INFO     Archive unpacked!
2015-05-12 18:06:27,427 root         INFO     New layer ID for squashed content will be: 60447d4df47226abcc8224550cfa49582f2b2e400552e83167b2cac2f3d7726a
2015-05-12 18:06:27,428 root         INFO     Starting squashing...
2015-05-12 18:06:27,428 root         INFO     Squashing layer 8fc76b1b4170a0ec291f0f8764d6fda6eec49b35478f668863ffd5929f298b59...
2015-05-12 18:06:27,428 root         INFO     Squashing layer 3be96d4576bfda0d8c4f1a64f5e8b6fac537f65c321909850f8897afe833de15...
2015-05-12 18:06:27,428 root         INFO     Squashing layer 77e7705293eb903586e61f194329689d612389dd59026fe0c906c2133ee67c65...
Traceback (most recent call last):
  File "/root/.local/bin/docker-scripts", line 9, in <module>
    load_entry_point('docker-scripts==0.3.2', 'console_scripts', 'docker-scripts')()
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 87, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 82, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 30, in run_squash
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 411, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 245, in _squash_layers
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 124, in _marker_files
  File "/usr/lib64/python2.7/tarfile.py", line 1805, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib64/python2.7/tarfile.py", line 2380, in _load
    tarinfo = self.next()
  File "/usr/lib64/python2.7/tarfile.py", line 2319, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1242, in fromtarfile
    return obj._proc_member(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1264, in _proc_member
    return self._proc_pax(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1394, in _proc_pax
    value = value.decode("utf8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 4: invalid start byte
```

you can reproduce this by cloning github.com/openshift/sti-perl and running "make test"

**Comment by bparees** [comment]
(ok you can't do that now because i reverted the change to do squashing, but if you checkout the previous commit in that repo, you should be able to reproduce it)

**Comment by goldmann** [comment]
Thanks for the report, I could reproduce it. Working on a fix now.

**Comment by goldmann** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1194473

**Comment by goldmann** [comment]
This is now fixed. Thanks to @vbatts for the idea how to solve it!

**Comment by bparees** [comment]
@goldmann thanks! looks like it's working for me now.  thanks @vbatts.

**Comment by vbatts** [comment]
:+1:
