### ISSUE TITLE
Incompatibility with old python-six package: AttributeError: '_MovedItems' object has no attribute 'range'

### ISSUE THREAD

**Issue by goldmann** [goldmann/docker-scripts#19]
```
2015-05-20T06:20:54.692561024Z 2015-05-20 02:20:54,688 - dock.plugin - DEBUG - Traceback (most recent call last):
2015-05-20T06:20:54.692561024Z   File "/usr/lib/python2.7/site-packages/dock/plugin.py", line 211, in run
2015-05-20T06:20:54.692561024Z     plugin_response = plugin_instance.run()
2015-05-20T06:20:54.692561024Z   File "/usr/lib/python2.7/site-packages/dock/plugins/prepub_squash.py", line 58, in run
2015-05-20T06:20:54.692561024Z     from_layer=self.from_layer, tag=self.tag).run()
2015-05-20T06:20:54.692561024Z   File "/usr/lib/python2.7/site-packages/docker_scripts/squash.py", line 388, in run
2015-05-20T06:20:54.692561024Z     if not self._save_image(old_image_id, old_image_tar):
2015-05-20T06:20:54.692561024Z   File "/usr/lib/python2.7/site-packages/docker_scripts/squash.py", line 66, in _save_image
2015-05-20T06:20:54.692561024Z     for x in six.moves.range(3):
2015-05-20T06:20:54.692561024Z AttributeError: '_MovedItems' object has no attribute 'range'
```

**Comment by goldmann** [comment]
```
# python
Python 2.7.5 (default, Feb 11 2014, 07:46:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>> six.moves.range(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_MovedItems' object has no attribute 'range'
```

```
# rpm -q python-six
python-six-1.3.0-4.el7.noarch
```

**Comment by TomasTomecek** [comment]
or you could write that function yourself, something like:
```python
range_function = None
try:
  range_function = xrange  # py 2
except NameError:
  range_function = range  # py 3
for x in range_function(3):
  ...
```

anyway, thanks for fixing this!

**Comment by goldmann** [comment]
True, true, although this was the only place where I used it. I'll think about it when I'll need it it more places.
