### ISSUE TITLE
Getting client incompatibility because of docker_py 1.3.0

### ISSUE THREAD

**Issue by mfojtik** [goldmann/docker-scripts#35]
```console
Traceback (most recent call last):
  File "/root/.local/bin/docker-scripts", line 9, in <module>
    load_entry_point('docker-scripts==0.4.2', 'console_scripts', 'docker-scripts')()
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 91, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 86, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 30, in run_squash
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 48, in __init__
  File "build/bdist.linux-x86_64/egg/docker_scripts/lib/common.py", line 37, in docker_client
  File "build/bdist.linux-x86_64/egg/docker_scripts/lib/common.py", line 52, in valid_docker_connection
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.3.0-py2.7.egg/docker/client.py", line 563, in ping
    return self._result(self._get(self._url('/_ping')))
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.3.0-py2.7.egg/docker/clientbase.py", line 106, in _result
    self._raise_for_status(response)
  File "/root/.local/lib/python2.7/site-packages/docker_py-1.3.0-py2.7.egg/docker/clientbase.py", line 102, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.19, server: 1.18)")
```

Solution:

```
$ easy_install --user docker_py==1.2.3 docker-scripts==0.4.2
```

**Comment by mfojtik** [comment]
@goldmann FYI

**Comment by TomasTomecek** [comment]
You can use [AutoVersionClient](https://github.com/docker/docker-py/blob/826c9e676af8052e924ec3c280ba9c9f73b1cda5/docker/client.py#L834).

**Comment by goldmann** [comment]
I'm back from vacations and will look at it ASAP, thanks!
