### ISSUE TITLE
Cleanup temporary directory when "no space left on device" error occurs

### ISSUE THREAD

**Issue by php-coder** [goldmann/docker-scripts#44]
When I run docker-scripts and during image squashing error occurs, it doesn't remove temporary directory after it fails:

```
2015-10-08 08:51:10,796 root         INFO     Squashing image 'centos/php-56-centos7'...
2015-10-08 08:51:10,873 root         INFO     Old image has 17 layers
2015-10-08 08:51:10,873 root         INFO     Attempting to squash from layer 8b2142fa4463437efd3a3460d8a1d13d6d841cd56e9b89d48d12892956e985c4...
2015-10-08 08:51:10,873 root         INFO     Checking if squashing is necessary...
2015-10-08 08:51:10,873 root         INFO     We have 11 layers to squash
2015-10-08 08:51:10,875 root         INFO     Saving image f145f0473731f303f6a3479339a1f18133e043c9486d46f11e40374a76759d8f to /tmp/docker-squash-n3ST8m/image.tar file...
2015-10-08 08:51:34,122 root         INFO     Image saved!
2015-10-08 08:51:34,217 root         INFO     Unpacking /tmp/docker-squash-n3ST8m/image.tar tar file to /tmp/docker-squash-n3ST8m/old directory
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/docker-scripts", line 9, in <module>
    load_entry_point('docker-scripts==0.4.2', 'console_scripts', 'docker-scripts')()
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 91, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 86, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/cli.py", line 30, in run_squash
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 471, in run
  File "build/bdist.linux-x86_64/egg/docker_scripts/squash.py", line 91, in _unpack
  File "/usr/lib64/python2.7/tarfile.py", line 2051, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib64/python2.7/tarfile.py", line 2088, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib64/python2.7/tarfile.py", line 2164, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python2.7/tarfile.py", line 2205, in makefile
    copyfileobj(source, target)
  File "/usr/lib64/python2.7/tarfile.py", line 265, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
...
$ ll /tmp/
total 0
drwx------. 3 vagrant vagrant 80 Oct  8 08:51 docker-squash-n3ST8m
```

**Comment by goldmann** [comment]
Basically - this is on purpose. I was thinking about it earlier. Consider following situation where squashing fails and you're going to see what was the cause. If I would cleanup stuff - you would not be able to see the temporary generated files and could not compare if what you're expecting. In general - cleaning up may seem as a good idea in the first glance, but while I was developing and breaking things in many ways - I would be not so happy to have it cleaned up :)

**Comment by php-coder** [comment]
I'm agree that it may be useful for developers but IMHO it's better to disable this behavior by default and allow to developer enable it with command line option when he/she **really** wants such behavior.

If you won't change this behavior, could you please, add extra message about temporary folder that user should inspect and/or delete. Also I believe that such situations should be handled more gracefully and don't show stack trace to the user.

**Comment by goldmann** [comment]
I think I could introduce a `--dev` switch and catch all errors in other case.

**Comment by php-coder** [comment]
BTW, `s2i` has option `--save-temp-dir` that looks like doing the same thing.

**Comment by goldmann** [comment]
I hope my implementation will make you happy :)
