### ISSUE TITLE
Traceback with docker-1.10

### ISSUE THREAD

**Issue by twaugh** [goldmann/docker-scripts#48]
In docker-1.10 the format created by `docker save` surprises docker-scripts, causing a traceback.

```
[root@localhost ~]# docker build -t hello-world --rm .
Sending build context to Docker daemon 849.3 MB
Step 1 : FROM fedora
 ---> 7f514965bc71
Step 2 : MAINTAINER Tim Waugh <twaugh@redhat.com>
 ---> Running in 252c27f858a8
 ---> f154af43571d
Removing intermediate container 252c27f858a8
Step 3 : ENV env foo
 ---> Running in 8868d683113f
 ---> ca23b29d5e98
Removing intermediate container 8868d683113f
Step 4 : CMD printf hello world
 ---> Running in 5fef2b292ca8
 ---> 04180b30b127
Removing intermediate container 5fef2b292ca8
Successfully built 04180b30b127
[root@localhost ~]# docker history hello-world
IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
04180b30b127        About a minute ago   /bin/sh -c #(nop) CMD ["/bin/sh" "-c" "printf   0 B                 
ca23b29d5e98        About a minute ago   /bin/sh -c #(nop) ENV env=foo                   0 B                 
f154af43571d        About a minute ago   /bin/sh -c #(nop) MAINTAINER Tim Waugh <twaug   0 B                 
7f514965bc71        11 days ago          /bin/sh -c #(nop) ADD file:f867e28f7b12f9d64d   204 MB              
86c04d55e004        4 months ago         /bin/sh -c #(nop) MAINTAINER Adam Miller <max   0 B                 
[root@localhost ~]# docker-scripts squash hello-world -t hello-world-squashed -f f154af43571d
2015-12-02 11:55:50,010 root         INFO     Running version 0.4.4, Docker 669c279-dirty, API 1.22...
2015-12-02 11:55:50,010 root         INFO     Squashing image 'hello-world'...
2015-12-02 11:55:50,023 root         INFO     Old image has 5 layers
2015-12-02 11:55:50,023 root         INFO     Attempting to squash from layer sha256:f154af43571daa042210fab21c7dd7ee2b31623bc5ab47547c82be80bbf4e11d...
2015-12-02 11:55:50,023 root         INFO     Checking if squashing is necessary...
2015-12-02 11:55:50,023 root         INFO     We have 2 layers to squash
2015-12-02 11:55:50,025 root         INFO     Saving image sha256:04180b30b127c416739b3408a926220cf13dbe44833a1b8c7c9114a7c9c2e298 to /tmp/docker-squash-yVCfjY/image.tar file...
2015-12-02 11:55:54,616 root         INFO     Image saved!
2015-12-02 11:55:54,628 root         INFO     Unpacking /tmp/docker-squash-yVCfjY/image.tar tar file to /tmp/docker-squash-yVCfjY/old directory
2015-12-02 11:55:54,782 root         INFO     Archive unpacked!
2015-12-02 11:55:54,782 root         INFO     New layer ID for squashed content will be: a551939d6a79381de09c6fe55c97eba952efaccd24240f237c747c7566b8e30b
2015-12-02 11:55:54,782 root         INFO     Starting squashing...
2015-12-02 11:55:54,782 root         INFO     Squashing layer 'sha256:04180b30b127c416739b3408a926220cf13dbe44833a1b8c7c9114a7c9c2e298'...
Traceback (most recent call last):
  File "/usr/bin/docker-scripts", line 9, in <module>
    load_entry_point('docker-scripts==0.4.4', 'console_scripts', 'docker-scripts')()
  File "/usr/lib/python2.7/site-packages/docker_scripts/cli.py", line 96, in run
    cli.run()
  File "/usr/lib/python2.7/site-packages/docker_scripts/cli.py", line 88, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/docker_scripts/cli.py", line 31, in run_squash
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir).run()
  File "/usr/lib/python2.7/site-packages/docker_scripts/squash.py", line 497, in run
    layers_to_squash, layers_to_move, squashed_tar, old_image_dir)
  File "/usr/lib/python2.7/site-packages/docker_scripts/squash.py", line 337, in _squash_layers
    with tarfile.open(layer_tar_file, 'r', format=tarfile.PAX_FORMAT) as layer_tar:
  File "/usr/lib64/python2.7/tarfile.py", line 1667, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib64/python2.7/tarfile.py", line 1732, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/lib64/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: u'/tmp/docker-squash-yVCfjY/old/sha256:04180b30b127c416739b3408a926220cf13dbe44833a1b8c7c9114a7c9c2e298/layer.tar'
```

**Comment by twaugh** [comment]
FWIW this was with https://github.com/docker/docker/commit/900c8f5.

**Comment by goldmann** [comment]
This affects also `layers` subcommand.

**Comment by goldmann** [comment]
With current version of `1.10` it's impossible to get `Parent` of the image when using `inspect` call:

```
Server:
 Version:         1.10.0-dev
 API version:     1.22
 Package version: 
 Go version:      go1.5.1
 Git commit:      e75da4b
 Built:           Wed Dec  2 00:31:00 UTC 2015
 OS/Arch:         linux/amd64
```

**Comment by goldmann** [comment]
The issue is that starting with 1.10 Docker is hiding information about layers to end user. This unfortunately makes it very hard to get list of layers which is required to both `layers` and `squash` subcommands. I consider this an incompatible change in Docker and I do not understand why it was introduced. Moreover - I do not see any benefit in that change. With 1.10 Docker is exposing images as more monolithic creations where we should not see how these were built and what layers these images contain. This is a big shift compared to what Docker advertised since beginning where layers were highlighted as first class citizen (regular images).

Of course this change breaks any software which is working the area of image creation/modification.

**Comment by goldmann** [comment]
By saying incompatible I mean that it'll be not possible to get (easily?) list of layers from images built on previous versions of Docker:

```
$ docker history jboss/wildfly:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
6d658fcccab0        2 weeks ago         /bin/sh -c #(nop) CMD ["/opt/jboss/wildfly/bi   0 B                 
<missing>           2 weeks ago         /bin/sh -c #(nop) EXPOSE 8080/tcp               0 B                 
<missing>           2 weeks ago         /bin/sh -c #(nop) ENV LAUNCH_JBOSS_IN_BACKGRO   0 B                 
<missing>           2 weeks ago         /bin/sh -c cd $HOME     && curl -O https://do   159.1 MB            
<missing>           2 weeks ago         /bin/sh -c #(nop) ENV JBOSS_HOME=/opt/jboss/w   0 B                 
<missing>           2 weeks ago         /bin/sh -c #(nop) ENV WILDFLY_SHA1=75738379f7   0 B                 
<missing>           2 weeks ago         /bin/sh -c #(nop) ENV WILDFLY_VERSION=9.0.2.F   0 B                 
<missing>           3 months ago        /bin/sh -c #(nop) ENV JAVA_HOME=/usr/lib/jvm/   0 B                 
<missing>           3 months ago        /bin/sh -c #(nop) USER [jboss]                  0 B                 
<missing>           3 months ago        /bin/sh -c yum -y install java-1.8.0-openjdk-   195.3 MB            
<missing>           3 months ago        /bin/sh -c #(nop) USER [root]                   0 B                 
<missing>           3 months ago        /bin/sh -c #(nop) MAINTAINER Marek Goldmann <   0 B                 
<missing>           5 months ago        /bin/sh -c #(nop) USER [jboss]                  0 B                 
<missing>           5 months ago        /bin/sh -c #(nop) WORKDIR /opt/jboss            0 B                 
<missing>           5 months ago        /bin/sh -c groupadd -r jboss -g 1000 && usera   294.8 kB            
<missing>           5 months ago        /bin/sh -c yum update -y && yum -y install xm   57.58 MB            
<missing>           5 months ago        /bin/sh -c #(nop) MAINTAINER Marek Goldmann <   0 B                 
<missing>           5 months ago        /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
<missing>           5 months ago        /bin/sh -c #(nop) ADD file:82835f82606420c764   172.2 MB            
<missing>           7 months ago        /bin/sh -c #(nop) MAINTAINER The CentOS Proje   0 B  
```

But if you build this image:

```
FROM fedora:latest
RUN uname -a && env
```

with new 1.10 (pre), you get:

```
$ docker history 261c9b6e5f23
IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
sha256:261c9        About a minute ago   /bin/sh -c uname -a && env                      0 B                 
sha256:7f514        12 days ago          /bin/sh -c #(nop) ADD file:f867e28f7b12f9d64d   204 MB              
<missing>           4 months ago         /bin/sh -c #(nop) MAINTAINER Adam Miller <max   0 B 
```

I do not understand why the latest layer (which is part of `fedora:latest` image which was built using stable version of Docker on Docker HUB) does not have it's ID printed. Additionally text `<missing>` is completely misleading and simply untrue.

Adding to this the empty `Parent` in `docker inspect` output - it makes it very hard to investigate images now, without a reason.

**Comment by goldmann** [comment]
To even more clearly show the issue of incompatibility between old and new layers:

```
$ ./docker-1.10.0-dev history e8907b3544f6     
IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
e8907b3544f6        39 seconds ago       /bin/sh -c #(nop) CMD ["/opt/jboss/wildfly/bi   0 B                 
9e54cbe01e82        43 seconds ago       /bin/sh -c #(nop) EXPOSE 8080/tcp               0 B                 
ec14368e8e09        48 seconds ago       /bin/sh -c #(nop) ENV LAUNCH_JBOSS_IN_BACKGRO   0 B                 
212fc1c312b0        51 seconds ago       /bin/sh -c cd $HOME     && curl -O https://do   167.2 MB            
674f04b7d4f8        About a minute ago   /bin/sh -c #(nop) ENV JBOSS_HOME=/opt/jboss/w   0 B                 
c4c49ca8672c        About a minute ago   /bin/sh -c #(nop) ENV WILDFLY_SHA1=b740a18b3b   0 B                 
f5f8ae644419        About a minute ago   /bin/sh -c #(nop) ENV WILDFLY_VERSION=10.0.0.   0 B                 
380ae523f33f        3 months ago         /bin/sh -c #(nop) ENV JAVA_HOME=/usr/lib/jvm/   0 B                 
<missing>           3 months ago         /bin/sh -c #(nop) USER [jboss]                  0 B                 
<missing>           3 months ago         /bin/sh -c yum -y install java-1.8.0-openjdk-   195.3 MB            
<missing>           3 months ago         /bin/sh -c #(nop) USER [root]                   0 B                 
<missing>           3 months ago         /bin/sh -c #(nop) MAINTAINER Marek Goldmann <   0 B                 
<missing>           5 months ago         /bin/sh -c #(nop) USER [jboss]                  0 B                 
<missing>           5 months ago         /bin/sh -c #(nop) WORKDIR /opt/jboss            0 B                 
<missing>           5 months ago         /bin/sh -c groupadd -r jboss -g 1000 && usera   294.8 kB            
<missing>           5 months ago         /bin/sh -c yum update -y && yum -y install xm   57.58 MB            
<missing>           5 months ago         /bin/sh -c #(nop) MAINTAINER Marek Goldmann <   0 B                 
<missing>           5 months ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
<missing>           5 months ago         /bin/sh -c #(nop) ADD file:82835f82606420c764   172.2 MB            
<missing>           7 months ago         /bin/sh -c #(nop) MAINTAINER The CentOS Proje   0 B 
```

**Comment by goldmann** [comment]
Just a small update - I'm working on a fix right now. I do see some light in the tunnel :) Hope to have something next week that will work.

**Comment by goldmann** [comment]
I managed to run almost all integration and unit tests both for v1 and v2 format (in both Python 2.7 and 3.4). Next step is to refactor the code to make it clean and write another set of integration/unit tests.

I'm also working on a CI solution that would let me test docker-scripts with different Docker versions.

**Comment by goldmann** [comment]
I think this one can be closed now. There is no traceback i the v2 branch. Now I'm working on improving it.

**Comment by rassie** [comment]
I suppose v2 branch is not available publicly?

**Comment by goldmann** [comment]
It is, sorta ;) Was merged with master today ;)
