### ISSUE TITLE
Squashing fails with "ApplyLayer exit status 1 stdout:  stderr: no such file or directory" or similar

### ISSUE THREAD

**Issue by goldmann** [goldmann/docker-scripts#50]
Log:

```
2016-02-04 13:43:43,744 root         DEBUG    Moving unmodified layer '1962253fc10cf35c44d0990bc68291c6b32e8d5c1bda66e4dee2370b2a00c8af'...
2016-02-04 13:43:43,744 root         DEBUG    Moving unmodified layer 'af5068b1ae3eb2e20cf9d94ebcc6df1691725339243262eeb61b48a0a77abc67'...
2016-02-04 13:43:43,745 root         INFO     Squashed image name: squashed:latest
2016-02-04 13:43:43,745 root         DEBUG    Generating tar archive for the squashed image...
2016-02-04 13:43:44,243 root         DEBUG    Archive generated
2016-02-04 13:43:44,243 root         DEBUG    Loading squashed image...
2016-02-04 13:43:51,325 requests.packages.urllib3.connectionpool DEBUG    "POST /v1.21/images/load HTTP/1.1" 404 105
Traceback (most recent call last):
  File "/home/goldmann/.local/bin/docker-scripts", line 9, in <module>
    load_entry_point('docker-scripts==0.4.4', 'console_scripts', 'docker-scripts')()
  File "/home/goldmann/.local/lib/python2.7/site-packages/docker_scripts/cli.py", line 96, in run
    cli.run()
  File "/home/goldmann/.local/lib/python2.7/site-packages/docker_scripts/cli.py", line 88, in run
    args.func(args)
  File "/home/goldmann/.local/lib/python2.7/site-packages/docker_scripts/cli.py", line 31, in run_squash
    from_layer=args.from_layer, tag=args.tag, output_path=args.output_path, tmp_dir=args.tmp_dir).run()
  File "/home/goldmann/.local/lib/python2.7/site-packages/docker_scripts/squash.py", line 520, in run
    self._load_image(new_image_dir)
  File "/home/goldmann/.local/lib/python2.7/site-packages/docker_scripts/squash.py", line 223, in _load_image
    self.docker.load_image(buf.getvalue())
  File "/home/goldmann/.local/lib/python2.7/site-packages/docker/api/image.py", line 148, in load_image
    self._raise_for_status(res)
  File "/home/goldmann/.local/lib/python2.7/site-packages/docker/client.py", line 141, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("ApplyLayer exit status 1 stdout:  stderr: chtimes /opt/webserver/webapps/ROOT: no such file or directory")
```

Docker daemon log:

```
Feb 04 13:43:45 mistress docker[396]: time="2016-02-04T13:43:45.162110621+01:00" level=debug msg="Calling POST /v1.21/images/load"
Feb 04 13:43:45 mistress docker[396]: time="2016-02-04T13:43:45.162138096+01:00" level=debug msg="POST /v1.21/images/load"
Feb 04 13:43:45 mistress docker[396]: time="2016-02-04T13:43:45.162935119+01:00" level=info msg="{Action=load, Username=goldmann, LoginUID=1000, PID=634}"
Feb 04 13:43:46 mistress docker[396]: time="2016-02-04T13:43:46.260096970+01:00" level=debug msg="Loading d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe"
Feb 04 13:43:46 mistress docker[396]: time="2016-02-04T13:43:46.765199610+01:00" level=debug msg="[deviceset] AddDevice(hash=d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe basehash=af5068b1ae3eb2e20cf9d94ebcc6df1691725339243262eeb61b48a0a77abc67)"
Feb 04 13:43:46 mistress docker[396]: time="2016-02-04T13:43:46.780599317+01:00" level=debug msg="registerDevice(4678, d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:46 mistress docker[396]: time="2016-02-04T13:43:46.793644342+01:00" level=debug msg="[deviceset] AddDevice(hash=d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe basehash=af5068b1ae3eb2e20cf9d94ebcc6df1691725339243262eeb61b48a0a77abc67) END"
Feb 04 13:43:46 mistress docker[396]: time="2016-02-04T13:43:46.795614828+01:00" level=debug msg="activateDeviceIfNeeded(d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:46 mistress docker[396]: time="2016-02-04T13:43:46.848969915+01:00" level=debug msg="Start untar layer"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.007371332+01:00" level=debug msg="[devmapper] UnmountDevice(hash=d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.007400305+01:00" level=debug msg="[devmapper] Unmount(/var/lib/docker/devicemapper/mnt/d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.418713471+01:00" level=debug msg="[devmapper] Unmount done"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.418811361+01:00" level=debug msg="[devmapper] deactivateDevice(d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.418936583+01:00" level=debug msg="[devmapper] removeDevice START(docker-253:4-5242881-d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.440845525+01:00" level=debug msg="[devmapper] removeDevice END(docker-253:4-5242881-d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.440878944+01:00" level=debug msg="[devmapper] deactivateDevice END(d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.440889454+01:00" level=debug msg="[devmapper] UnmountDevice(hash=d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe) END"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.442179582+01:00" level=debug msg="devmapper: DeleteDevice(hash=d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe syncDelete=false) START"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.442192741+01:00" level=debug msg="devmapper: issueDiscard(device: d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe). START"
Feb 04 13:43:49 mistress docker[396]: time="2016-02-04T13:43:49.442200543+01:00" level=debug msg="activateDeviceIfNeeded(d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.271166347+01:00" level=debug msg="devmapper: issueDiscard(device: d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe). END"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.271200577+01:00" level=debug msg="[devmapper] deactivateDevice(d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.271260569+01:00" level=debug msg="[devmapper] removeDevice START(docker-253:4-5242881-d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.296791905+01:00" level=debug msg="[devmapper] removeDevice END(docker-253:4-5242881-d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.296825740+01:00" level=debug msg="[devmapper] deactivateDevice END(d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.317886433+01:00" level=debug msg="unregisterDevice(4678, d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe)"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.320975273+01:00" level=debug msg="devmapper: DeleteDevice(hash=d500bc3c8bd13630b7536b2116cd0a68de1172876c0befb295c3314df66f2cfe syncDelete=false) END"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.321682713+01:00" level=error msg="Handler for POST /v1.21/images/load returned error: ApplyLayer exit status 1 stdout:  stderr: chtimes /opt/webserver/webapps/ROOT: no such file or directory"
Feb 04 13:43:51 mistress docker[396]: time="2016-02-04T13:43:51.322406201+01:00" level=error msg="HTTP Error" err="ApplyLayer exit status 1 stdout:  stderr: chtimes /opt/webserver/webapps/ROOT: no such file or directory" statusCode=404
```

**Comment by goldmann** [comment]
Added file has following permissions and date:

```
-rw-r--r-- 0/0               0 1970-01-01 01:00 deployments/.wh.ROOT
```

**Comment by goldmann** [comment]
Most probably it fails in this line: https://github.com/docker/docker/blob/v1.9.1/pkg/archive/diff.go#L237

**Comment by goldmann** [comment]
I could not reproduce it for now, closing.
